-- SQL schema for Supabase tables

-- Additional user profile linked to Supabase auth.users
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  username text,
  created_at timestamp with time zone default now()
);

-- Conversations owned by a user
create table if not exists public.conversations (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references public.profiles(id) on delete cascade,
  created_at timestamp with time zone default now()
);

-- Messages exchanged in a conversation
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.conversations(id) on delete cascade,
  sender text not null,
  content text not null,
  created_at timestamp with time zone default now()
);

-- Enable Row Level Security as needed
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

